### ISSUE TITLE
Invoeren van een 'wis-log'

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/GE-scripts#15]
Naar aanleiding van een discussie op het forum over gewiste objecten. Alle wijzigingen aan objecten worden gelogd, maar bij wissen wordt ook deze log verwijderd. Dat is geen probleem, maar het is daardoor niet meer te achterhalen wie of waarom een entiteit gewist werd. Idee is nu om bij wissen een optioneel veld 'reden' door te voeren, waarbij na wissen van het object het ID-nummer, de roepnaam en de ingegeven reden voor wissen gelogd blijven, liefst inzichtelijk via de backend en voor iedereen met beheerdersrechten. Zo kan men van elkaar zien waarom een bepaald object gewist werd en worden discussies of vragen voorkomen.

**Comment by HansNien** [comment]
Hmm, per ongeluk in het verkeerde draadje geplaatst. Ik plaats hem opnieuw in de goede. Deze mag nu zelf gewist worden. Pardon voor het ongemak.

**Comment by BaDu-HSN** [comment]
CLOSED
