### ISSUE TITLE
Een enkele sessie per IP

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/GE-scripts#23]
Op dit moment komen er gelijktijdige meerdere (2 of 3) gelijke viewqueries binnen.
Dat duidt er op dat en mensen zijn die meerdere keren de netkaart in hun Mij Plaatsen boom hebben staan. Dit is ongewenst en geeft een onnodig hoge server load.
Dit komt metname voor in de GE-kaart de webkaart heeft hier geen last van.

Oplossing is per sessie een open kaart toe te staan.

**Comment by Knarvel** [comment]
Ja, daar herken ik me in... de reden is simpel, objecten die niet binnen de actuele vieuwport
 de actuele vieuwport staan, staan ook niet meer in de tree links. dus op een op het object dubbel-klikken om de actuele vieuwport daarheen te verplaatsen kan dus niet meer. Ook objecten die wel in de huidige view zitten maar om datum-redenen niet zichtbaar zijn kunnen alleen op deze manier aangesproken worden. Vandaar heb ik naast de dynamische kaart ook een exemplaar van de volledige download in de tree staan.
Ik zal om het datavolume niet uit de hand te laten lopen de "schaduw-kaart"alleen dan inschakelen al ik het actueel nodig heb... 
Als er hier een beperking ingebouwd gaat worden, dan graag 2 kaarten per sessie toestaan

**Comment by BaDu-HSN** [comment]
De schaduwkaart vreet geen resources op de server (alleen bij de generatie), dus dezeconstructie is geen probleem

**Comment by BaDu-HSN** [comment]
This issue was moved to Hoogspanningsnet/Netkaart-scripts#7
